db/mc6809

https://github.com/radare/radare2-extras/pull/57
Visually checked against existing definitions.

Add definition for MC6809 disassembler in r2-extras PR #57

---

db/libdwarf

On ubuntu12.04, `pkg-config` is not working for `libelf-dev` hence travis for `r2pm -i dwarf-parser` is failing. Hopefully this should fix that issue.

remove check for libelf and zlib for travis build

---

db/r2-lua53
db/r2api-lua
db/r2b-lua

According to the Lua website,[1] only the first letter of "Lua"
should be capitalized, so do the same in the package descriptions
here. Also, while we're at it, fix the capitalization of SWIG and
tweak the word order too.
[1] https://www.lua.org/about.html

Fix capitalization of "Lua" in package descriptions

---

db/iaito

Here is an attempt at fixing the installation process on Linux. This PR tries to fix two things:
1. add `gcc_64 `as a PATH candidate
2. link to the correct binary on Linux
This is not enough for a user installation as the following script needs to be created:
```
$ cat iaito 
#!/bin/sh
$RADARE_GIT_PATH/radare2/env.sh '$HOME/bin/prefix/radare2/' $HOME/.config/radare2/prefix/bin/iaito' "$@"
```
Shall this PR also attempts to create this wrapper ?

Fix iaito install path

---

db/mc6809

I needed to do this to stop "r2pm install mc6809" giving me this:
/home/daniel/.config/radare2/r2pm/db/mc6809: line 17: unexpected EOF while looking for matching `"'
/home/daniel/.config/radare2/r2pm/db/mc6809: line 21: syntax error: unexpected end of file
/usr/bin/r2pm: line 389: R2PM_INSTALL: command not found

Fix broken quote in mc6809 install script

---

db/pyc

Fix `r2pm -i pyc` doesn't build asm_pyc for pyc architecture.

r2pm build asm_pyc

---

db/retdec

With radare/radare2#15033, fix retdec installation by changing install dir from e.g `retdec/retdec/bin` to `retdec/bin`.

Fix retdec installation

---

db/lang-python

For some reason, `gmake python` always returns "Nothing to be done for 'python'", possibly due to the existing `python` directory.

Use `py` instead of `python` as make argument.

---

db/libmc7

Library to disassemble MC7 bytecode for Siemens PLC SIMATIC S7-300 and S7-400

libmc7 for S7-300 Bytecode

---

db/retdec-r2plugin

Hi! In this PR I would like to provide a package entry for the Avast's [retdec-r2plugin](https://github.com/avast/retdec-r2plugin).
The provided script will install not only the plugin but the bundled RetDec version as well. The reason for this is that not everyone will want to install their own RetDec and the features that are implemented in the plugin were tested and verified to be working with the bundled version.
Thank you!

Add retdec-r2plugin package

---

db/yara

Yara repository tags must be fetched before checking out.

Fetch tags before installation

---

db/yara

New version of Yara is available: https://github.com/VirusTotal/yara/releases/tag/v4.0.1

Bump yara version to 4.0.1

---

db/ba2

Adding support for NXP Beyond Architecture 2 CPU disassembly and analysis. (Used for example in JN5169 ZigBee CPU).
...
**Test plan**
I opened a few .elf files for this CPU.

Adding support for BA2 CPU

---

db/yara

New bugfix version of yara: https://github.com/VirusTotal/yara/releases/tag/v4.0.2

Bump yara version to 4.0.2

---

db/blackfin

When compiling blackfin with `r2pm -i blackfin` you would get:
```
gmake: *** No rule to make target 'blackfin'.  Stop.
```

Fix blackfin compilation

---

db/r2dec
db/r2ghidra-dec
db/retdec-r2plugin

Based on https://github.com/radareorg/radare2/pull/17357#issuecomment-666164765 and https://github.com/radareorg/radare2/pull/17442#issuecomment-673539719, this pr sets the git dir for r2dec, r2ghidra-dec and retdec-r2plugin to be the same as the package name. This is so `r2pm ci` for those packages actually does clean.
Also, compiling retdec-r2plugin takes ages.
**Test plan**
`r2pm -ci r2dec` / `r2ghidra-dec` / `retdec-r2plugin` actually cleans the package's git dir.
...

Set git dir == package name for r2dec, r2ghidra-dec and retdec-r2plugin

---

db/rlang-duktape

GitHub CI on radare2-extras broke because `make clean` target tries to include config.mk which does not exist until
`./configure` is executed in radare2-rlang for rlang-duktape package.
**Test plan**
Merge this commit, and then I can retest CI on r2e.

rlang-duktape: Add missing configure step && ignore clean failure

---

db/yara

New bugfix version of yara: https://github.com/VirusTotal/yara/releases/tag/v4.0.4
**Test plan**
My personal tests and **test/extras/cmd/yara** tests are passing with the new version.

Bump yara version to 4.0.4

---

db/yara

New version of Yara is available: https://github.com/VirusTotal/yara/releases/tag/v4.0.5
**Test plan**
Tests are passing.

Bump to yara v4.0.5

---

db/yara

New version of Yara is available: https://github.com/VirusTotal/yara/releases/tag/v4.1.0
**Test plan**
Tests are passing.

Bump to yara v4.1.0

---

db/yara

New version of Yara is available: https://github.com/VirusTotal/yara/releases/tag/v4.1.1
**Test plan**
Tests are passing.
None

Bump to yara v4.1.1

---

db/r2ghidra-sleigh
db/yara

as per as release
https://github.com/radareorg/r2ghidra/releases/download/5.6.2/r2ghidra_sleigh-5.6.2.zip
already available 
Edit 2 - Bump Yara version to latest

Update r2ghidra-sleigh to 5.6.2

---

db/r2ghidra-sleigh

**Checklist**
Correction installing of r2ghidra-sleigh with -gi key
Before path it anyway installed into local folder
After patch, if -gi key is used, we just move unzipped folder from local folder into global

Correction of db/r2ghidra-sleigh

---

db/imcat

**Checklist**
Not everybody uses gcc.

use $(CC) instead of gcc in imcat for portability
