db/x86tab
Add an entry for the tab assembler to make it available under r2pm
Ref: radare/radare2#660
=> Add x86tab entry

db/chita
closes https://github.com/jpenalbae/chita/issues/2
=> Add chita package

db/www-enyo, db/www-m, db/www-p, db/www-t
Web UI are installed in release mode
Ref: https://github.com/radare/radare2-webui/pull/122
=> Making all UI to install in release mode

db/mdmp
Had a quick test of this by manually downloading the script and
manipulating parts of it. This seemed to be the cause of the problem.
Also took this as an opportunity to update the byline.
=> MDMP v1.1 - Removed PKG_CONFIG_PATH as it causes problems

db/libdwarf
Few edit:
1) How can I specify the destination directory to clone into?
2) Any better place to copy library and header files without sudo?
=> add libdwarf

db/dwarf-parser, db/libdwarf
Needs testing alongwith the commit: https://github.com/radare/radare2-extras/pull/101/commits/7ab36bd2663d7ac48c4f5b8eb472602c4345305a
If this is clear, I will add this to travis and some regression test :)
For testing, only thing necessary is to know if the dwarf core plugin is loaded while running r2.
=> add dwarf parser

db/r2com
r2com package info at https://github.com/newlog/r2com
=> Add r2com package

db/zig-masm32
=> Add zig-masm32

db/r2dec
script not tested yet. wait before merge.
=> r2dec for r2pm

db/r2yara
r2pm -i r2yara
or
sudo r2pm -gi r2yara
=> Module to install yara with r2 module inside

db/pimp
no more dirty hacks, using the plugin interface
=> pimp: wrapper not needed anymore

db/cutter
=> iaito -> cutter

db/r2wiki
Way to install r2wiki from r2pm
=> r2wiki for r2pm

db/r2dec
=> Updated r2dec

db/nios
Package for recently added r2-arch nios in radare2-extras.
https://github.com/radare/radare2-extras/blob/master/libr/asm/p/asm_nios.c
=> nios package

db/pyc
Add installation script of pyc's anal plugin(https://github.com/radareorg/radare2-extras/pull/237)
=> Add pyc's anal plugin.

db/yara
During installation, checkout a stable version of Yara.
...
=> Fix Yara to stable version

db/r2taint
It is an attempt to create static data flow tracking using esil emulation engine.
**Test plan**
Just run via #!pipe /path/to/taint.py -h
...
=> added r2taint

db/modality
**This pull request adds the modality package to r2pm, which integrates angr with radare2**
This can be tested by running `r2pm -i modality`, after installing the prerequisites (angr, termcolor, r2lang python)
=> Add modality package

db/r2graph
https://github.com/radareorg/radare2-extras/pull/261
Core plugin
Recursive graphs supporting.
Supports output format: colorful text, ascii art, dot, webgl 3d
**Test plan**
```
aaa
aGC; aGCd; aGCw; aGCv
s main; aGc; aGcd; aGcw; aGcv
s sym.imp.malloc; aGx; aGxd; aGxw; aGxv
```
...
=> added r2graph

db/jadx
=> Bump jadx (1.0.0 => 1.1.0)

db/baksmali
small fix to bump baksmali to latest version
=> Update baksmali version

db/yara
**Checklist**
https://github.com/VirusTotal/yara/releases/tag/v4.1.2
=> Bump to yara v4.1.2

db/r2flutch
=> Add r2flutch package

db/yara
Bump to yara version 4.2.1.
**Checklist**
=> Bump to yara 4.2.1

db/r2ghidra-sleigh
**Checklist**
Was changed PR for global installing without local installing
=> Correction of installing from user

db/libmc7
=> Update git url for libmc7

db/r2premium
=> Add r2premium package to r2pm

db/yara
**Checklist**
Bump to yara version 4.2.3 (https://github.com/VirusTotal/yara/releases/tag/v4.2.3).
=> Update yara version

db/r2yara
Update r2yara repository with the new URL.
**Checklist**
=> Update r2yara URL

db/r2d2
=> add r2d2 to db

db/vc4
**Checklist**
Update the `make` command for vc4 plugin to reflect the new make target.
=> Update vc4 plugin make command

db/apktool, db/r2ghidra-sleigh
=> Update r2ghidra-sleigh and apktool
